apiVersion: v1
kind: Pod
metadata:
  name: node-test
spec:
  containers:
    - name: node
      image: ghcr.io/ruddms936/helloworld-github-action/image:latest
      env:
        - name: ENV_TEST
          value: 'k8s_run'
