name: get tag

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run: echo "${{ github.event.release.tag_name }}"
